name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # add flutter_screenutil
  flutter_screenutil: ^3.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
       - assets/icon_bg_history.png
       - assets/image_splash_icon.png
       - assets/icon_intro.png
       - assets/icon_start_intro.png
       - assets/icon_intro_two.png
       - assets/icon_intro_three.png
       - assets/intro_4.png
       - assets/icon_start_five.png
       - assets/icon_start_six.png
       - assets/icon_next_intro.png
       - assets/icon_previour.png
       - assets/icon_arrow.png
       - assets/icon_navigation_menu.png
       - assets/icon_navigation_store.png
       - assets/icon_navigation_take_out.png
       - assets/icon_navigation_menu.png
       - assets/icon_navigation_office_site.png
       - assets/icon_navigation_question_naire.png
       - assets/icon_navigation_youtube.png
       - assets/icon_oil_soba_custom.png
       - assets/icon_topping_recommend.png
       - assets/icon_navigation_online_store.png
       - assets/value/en.json
       - assets/value/vi.json
   #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/font/bebas_regular.ttf
    - family: Myriad
      fonts:
        - asset: assets/font/myriad_pro_bold_semi_extended.ttf
    - family: SourceHanSanMedium
      fonts:
        - asset: assets/font/source_han_sans_medium.otf
    - family: SourceHanSanNormal
      fonts:
       - asset: assets/font/source_han_sans_normal.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
